version: '3'
services:
  postgres:
    image: docker-postgres
    build: ./database
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: postgres-container
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  node:
    image: docker-node
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgres:
        condition: service_healthy
    container_name: node-container
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - node-logs:/usr/app/logs
    command: ["sh", "-c", "npx prisma generate && npm run start:dev"]  

networks:
  default:
    driver: bridge

volumes:
  node-logs:
  postgres-data:
  postgres-logs:
  