version: '3'
services:
  node:
    image: docker-node
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    container_name: node-container
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: ["npm", "run", "start:dev"]

  postgres:
    image: docker-postgres
    build: ./database
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: postgres-container

networks:
  default:
    driver: bridge